apiVersion: v1
kind: Service
metadata:
  name: devflow-postgresql
  labels:
    app.kubernetes.io/name: devflow-postgresql
    app.kubernetes.io/part-of: devflow
spec:
  selector:
    app.kubernetes.io/name: devflow-postgresql
  ports:
    - name: postgresql
      port: 5432
      targetPort: postgresql
