apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: devflow-postgresql-ingress
  labels:
    app.kubernetes.io/part-of: devflow
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: devflow-postgresql
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: devflow-api
      ports:
        - protocol: TCP
          port: 5432
