"""link webhook deliveries to pipeline runs

Revision ID: f411f2e069b3
Revises: fb57ec5dd46f
Create Date: 2026-09-02 10:28:10.829141
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "f411f2e069b3"
down_revision: str | None = "fb57ec5dd46f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "github_webhook_deliveries",
        sa.Column("pipeline_run_id", sa.Uuid(), nullable=True),
    )
    op.create_unique_constraint(None, "github_webhook_deliveries", ["pipeline_run_id"])
    op.create_foreign_key(
        None,
        "github_webhook_deliveries",
        "pipeline_runs",
        ["pipeline_run_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.add_column(
        "pipeline_runs",
        sa.Column(
            "trigger_source",
            sa.String(length=20),
            server_default="manual",
            nullable=False,
        ),
    )
    op.add_column(
        "pipeline_runs",
        sa.Column("jenkins_queue_url", sa.String(length=500), nullable=True),
    )
    op.add_column(
        "pipeline_runs",
        sa.Column("trigger_error", sa.String(length=500), nullable=True),
    )
    op.create_check_constraint(
        "ck_pipeline_runs_trigger_source",
        "pipeline_runs",
        "trigger_source IN ('manual', 'github')",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "ck_pipeline_runs_trigger_source", "pipeline_runs", type_="check"
    )
    op.drop_column("pipeline_runs", "trigger_error")
    op.drop_column("pipeline_runs", "jenkins_queue_url")
    op.drop_column("pipeline_runs", "trigger_source")
    op.drop_constraint(None, "github_webhook_deliveries", type_="foreignkey")
    op.drop_constraint(None, "github_webhook_deliveries", type_="unique")
    op.drop_column("github_webhook_deliveries", "pipeline_run_id")
    # ### end Alembic commands ###
