"""add github webhook deliveries

Revision ID: fb57ec5dd46f
Revises: 2269e274ede5
Create Date: 2026-09-01 16:44:03.272652
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "fb57ec5dd46f"
down_revision: str | None = "2269e274ede5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "github_webhook_deliveries",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("delivery_id", sa.String(length=100), nullable=False),
        sa.Column("event_type", sa.String(length=50), nullable=False),
        sa.Column("repository_full_name", sa.String(length=200), nullable=False),
        sa.Column("git_ref", sa.String(length=500), nullable=True),
        sa.Column("commit_sha", sa.String(length=40), nullable=True),
        sa.Column("accepted", sa.Boolean(), nullable=False),
        sa.Column(
            "received_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("delivery_id"),
    )
    op.create_index(
        "ix_github_webhook_deliveries_received_at",
        "github_webhook_deliveries",
        ["received_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_github_webhook_deliveries_received_at",
        table_name="github_webhook_deliveries",
    )
    op.drop_table("github_webhook_deliveries")
    # ### end Alembic commands ###
